name: 'Workflow Manager Test RR'
description: 'Github PR Lifecycle Manager'
author: 'Teammates'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'

  token:
    required: true
    description: 'github token'

runs:
  using: 'node12'
  main: 'dist/index.js'
